version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://root:123@mongo:27017/
      - ME_CONFIG_BASICAUTH=False

  my-backend:
   build: .  
   restart: always  
   depends_on:     
       - mongo  
   ports:
       - 3001:3001   
   environment:     
        - MONGODB_URI=mongodb://root:123@mongo:27017/Mailbox?authSource=admin